### ISSUE TITLE
something wrong with the first attempt of installation

### ISSUE THREAD

**Issue by keeplearning-again** [horennel/LaTex-OCR_for_macOS#5]
Thanks for your repo! I met with some problems for the first time installing. After compelling, I move the application to the folder. But after I click the button, the error arises
<img width="260" alt="image" src="https://github.com/user-attachments/assets/9398a0de-9a40-4554-810a-f8e1ebb81856">
I am wondering if there is any problem in my installation process!

```
(latex)LaTex-OCR_for_macOS % python setup.py py2app -A
miniconda3/envs/latex/lib/python3.8/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
!!

        ********************************************************************************
        Requirements should be satisfied by a PEP 517 installer.
        If you are using pip, you can try `pip install --use-pep517`.
        ********************************************************************************

!!
  dist.fetch_build_eggs(dist.setup_requires)
running py2app
creating Desktop/latex_ocr/LaTex-OCR_for_macOS/build/bdist.macosx-11.1-arm64/python3.8-standalone/app
creating Desktop/latex_ocr/LaTex-OCR_for_macOS/build/bdist.macosx-11.1-arm64/python3.8-standalone/app/collect
creating Desktop/latex_ocr/LaTex-OCR_for_macOS/build/bdist.macosx-11.1-arm64/python3.8-standalone/app/temp
creating build/bdist.macosx-11.1-arm64/python3.8-standalone/app/lib-dynload
creating build/bdist.macosx-11.1-arm64/python3.8-standalone/app/Frameworks
*** creating application bundle: MyLatexOCR ***
Copy 'miniconda3/envs/latex/lib/python3.8/site-packages/py2app/apptemplate/prebuilt/main-arm64' -> 'Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/MacOS/MyLatexOCR'
sign ['Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/MacOS/MyLatexOCR']
Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/MacOS/MyLatexOCR: replacing existing signature
Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/MacOS/MyLatexOCR: signed app bundle with Mach-O thin (arm64) [MyLatexOCR]
Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app: replacing existing signature
Desktop/latex_ocr/LaTex-OCR_for_macOS/dist/MyLatexOCR.app: signed app bundle with Mach-O thin (arm64) [MyLatexOCR]
Done!
```

**Comment by horennel** [comment]
You might have deleted your virtual environment or project folder (LaTex-OCR_for_macOS), which is not recommended. MyLatexOCR.app still depends on them to run, as mentioned in the README.md.
  You can clone this project into a folder you don’t use frequently and redo the installation steps.
  By the way, are you a macOS 15 user? Based on my platform tests, the program is still functioning normally. There might be some bugs, but simply restarting the app should resolve them.

  你可能删除了你的虚拟环境或项目文件夹（LaTex-OCR_for_macOS），这是不行的。因为MyLatexOCR.app运行时依旧依赖他们，这一点在README.md中有提到。
  你可以将此项目克隆到不经常使用的文件夹下，然后重新执行安装步骤。
  另外请问你是macOS15的用户吗，经过我自己的平台测试后，此程序依旧正常使用，或许会有一些bug，但只需要重启app即可。

**Comment by RowenHa** [comment]
Hi there! I got the same issue and I found the reason, u can use **VPN with global mode** and relaunch the app again to let it access hugging face properly.

I run the app in the command line and get the traceback here:

```
(pix2text)
~/Code/LaTex-OCR_for_macOS
➞  dist/MyLatexOCR.app/Contents/MacOS/MyLatexOCR                  [git:main] ✔
[WARNING 2025-08-10 20:19:43,435 _showwarnmsg:112] /opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/torch/onnx/_internal/registration.py:162: OnnxExporterWarning: Symbolic function 'aten::scaled_dot_product_attention' already registered for opset 14. Replacing the existing function with new function. This is unexpected. Please report it on https://github.com/pytorch/pytorch/issues.
  warnings.warn(

[WARNING 2025-08-10 20:19:43,650 _showwarnmsg:112] /opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/torch/functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

[INFO] 2025-08-10 20:19:43,721 [RapidOCR] base.py:24: Using engine_name: onnxruntime
[INFO] 2025-08-10 20:19:43,722 [RapidOCR] main.py:55: Using /Users/ywu/.cnstd/1.2/ppocr/ch_PP-OCRv5_det/ch_PP-OCRv5_det_infer.onnx
[WARNING 2025-08-10 20:20:23,752 _prepare_model_files:116] Failed to download model from HuggingFace: We couldn't connect to 'https://huggingface.co' to load the files, and couldn't find them in the cached files.
Check your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.
[WARNING 2025-08-10 20:20:23,752 _prepare_model_files:117] Downloading model from CN OSS ...
[ERROR 2025-08-10 20:20:24,014 get_model_file:302] Failed downloading url https://sg-models.oss-cn-beijing.aliyuncs.com/pix2text/1.0/p2t-mfr-onnx.zip
Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connection.py", line 753, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x1464c6480>, 'Connection to huggingface.co timed out. (connect timeout=10)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /breezedeus/pix2text-mfr/resolve/main/preprocessor_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1464c6480>, 'Connection to huggingface.co timed out. (connect timeout=10)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1546, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1463, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 286, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 309, in _request_wrapper
    response = http_backoff(method=method, url=url, **params, retry_on_exceptions=(), retry_on_status_codes=(429,))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 310, in http_backoff
    response = session.request(method=method, url=url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 96, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/requests/adapters.py", line 688, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /breezedeus/pix2text-mfr/resolve/main/preprocessor_config.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x1464c6480>, 'Connection to huggingface.co timed out. (connect timeout=10)'))"), '(Request ID: b5273a1f-fbf5-404f-977e-73752d4e6a6a)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/utils/hub.py", line 470, in cached_files
    hf_hub_download(
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1010, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1117, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1661, in _raise_on_head_call_error
    raise LocalEntryNotFoundError(
huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/pix2text/latex_ocr.py", line 107, in _prepare_model_files
    model, processor = self._init_model(
                       ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/pix2text/latex_ocr.py", line 132, in _init_model
    processor = TrOCRProcessor.from_pretrained(model_dir, **more_processor_config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/processing_utils.py", line 1306, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/processing_utils.py", line 1365, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/models/auto/image_processing_auto.py", line 471, in from_pretrained
    raise initial_exception
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/models/auto/image_processing_auto.py", line 458, in from_pretrained
    config_dict, _ = ImageProcessingMixin.get_image_processor_dict(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/image_processing_base.py", line 338, in get_image_processor_dict
    resolved_image_processor_file = cached_file(
                                    ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/utils/hub.py", line 312, in cached_file
    file = cached_files(path_or_repo_id=path_or_repo_id, filenames=[filename], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/transformers/utils/hub.py", line 543, in cached_files
    raise OSError(
OSError: We couldn't connect to 'https://huggingface.co' to load the files, and couldn't find them in the cached files.
Check your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/cnstd/utils/utils.py", line 298, in get_model_file
    download(
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/cnstd/utils/utils.py", line 215, in download
    raise RuntimeError("Failed downloading url %s" % oss_url)
RuntimeError: Failed downloading url https://sg-models.oss-cn-beijing.aliyuncs.com/pix2text/1.0/p2t-mfr-onnx.zip

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ywu/Code/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/Resources/__boot__.py", line 153, in <module>
    _run()
  File "/Users/ywu/Code/LaTex-OCR_for_macOS/dist/MyLatexOCR.app/Contents/Resources/__boot__.py", line 147, in _run
    exec(compile(source, script, "exec"), globals(), globals())
  File "/Users/ywu/Code/LaTex-OCR_for_macOS/latex_ocr.py", line 198, in <module>
    LatexOrcApplication(name='').run()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ywu/Code/LaTex-OCR_for_macOS/latex_ocr.py", line 52, in __init__
    self.p2t = Pix2Text(analyzer_config=dict(model_name='mfd'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/pix2text/pix_to_text.py", line 84, in __init__
    self.latex_model = LatexOCR(**formula_config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/pix2text/latex_ocr.py", line 76, in __init__
    model_dir = self._prepare_model_files(root, model_backend, model_info)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/pix2text/latex_ocr.py", line 118, in _prepare_model_files
    get_model_file(
  File "/opt/miniconda3/envs/pix2text/lib/python3.12/site-packages/cnstd/utils/utils.py", line 309, in get_model_file
    raise ModelDownloadingError(message)
cnstd.utils.utils.ModelDownloadingError: Failed to download model: p2t-mfr-onnx.zip.
	Please open your VPN and try again.
	If this error persists, please follow the instruction at [CnSTD/CnOCR Doc](https://www.breezedeus.com/cnocr) to manually download the model files.
2025-08-10 20:20:24.100 MyLatexOCR[32468:2098671] Launch error
2025-08-10 20:20:24.100 MyLatexOCR[32468:2098671] Launch error
See the py2app website for debugging launch issues```
